// ==============================================================================
// DayFlow / WorkNest HRMS - Complete Enterprise Mock Dataset (55 Staff Members)
// Spanning 2025 - 2026 Complete 1-Year Operational Lifecycle
// ==============================================================================

import { EmployeeProfile, LeaveRequest, AttendanceRecord, PayrollRecord, AuditLog } from '../types';

export const ENTERPRISE_EMPLOYEES: EmployeeProfile[] = [
  // --- 1. Executive & Leadership ---
  {
    id: 'emp-01',
    userId: 'u-01',
    firstName: 'Sarah',
    lastName: 'Connor',
    designation: 'VP of Engineering',
    department: 'ENGINEERING',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2022-01-10',
    employmentType: 'FULL_TIME',
    phone: '+1 (555) 901-2849',
    about: 'Engineering executive leading high-performance distributed systems infrastructure and organizational technical vision.',
    jobLove: 'Empowering technical leaders and driving architectural excellence.',
    interests: 'Distributed Systems, Rust, High-Performance Computing, Marathon running.',
    skills: JSON.stringify(['Distributed Systems', 'System Architecture', 'Cloud Infrastructure', 'Go', 'Rust', 'Kubernetes']),
    user: { id: 'u-01', email: 'admin@dayflow.internal', employeeId: 'OISACON20220001', role: 'ADMIN', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-01-10' },
  },
  {
    id: 'emp-02',
    userId: 'u-02',
    firstName: 'Marcus',
    lastName: 'Vance',
    designation: 'Head of People & Culture',
    department: 'HUMAN_RESOURCES',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2022-02-15',
    employmentType: 'FULL_TIME',
    phone: '+1 (555) 782-9901',
    about: 'People Operations strategist committed to psychological safety, equitable compensation lattices, and progressive workforce policies.',
    jobLove: 'Fostering high-trust team cultures and shaping career growth frameworks.',
    interests: 'Workplace Psychology, Talent Analytics, Chess, Vinyl records.',
    skills: JSON.stringify(['Talent Operations', 'Workforce Analytics', 'Labor Law', 'Conflict Resolution', 'People Strategy']),
    user: { id: 'u-02', email: 'hr@dayflow.internal', employeeId: 'OIMAVA20220002', role: 'HR_MANAGER', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-02-15' },
  },
  {
    id: 'emp-03',
    userId: 'u-03',
    firstName: 'Alex',
    lastName: 'Chen',
    designation: 'Senior Software Architect',
    department: 'ENGINEERING',
    workLocation: 'Remote - California',
    dateOfJoining: '2023-03-01',
    employmentType: 'FULL_TIME',
    phone: '+1 (555) 019-2831',
    about: 'Passionate technologist dedicated to building scalable enterprise workforce solutions with human-first design principles.',
    jobLove: 'Solving challenging distributed systems bottlenecks and mentoring teammates.',
    interests: 'Cloud Architecture, Open Source AI, Hiking, Photography, Coffee brewing.',
    skills: JSON.stringify(['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'System Architecture', 'UI/UX']),
    user: { id: 'u-03', email: 'alex.chen@dayflow.internal', employeeId: 'OIALCH20230003', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-03-01' },
  },
  {
    id: 'emp-04',
    userId: 'u-04',
    firstName: 'Elena',
    lastName: 'Rodriguez',
    designation: 'Principal UI/UX Designer',
    department: 'DESIGN',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2023-04-12',
    employmentType: 'FULL_TIME',
    phone: '+1 (555) 441-8921',
    about: 'Product designer focusing on accessible, human-centric enterprise workflows and delightful spatial interfaces.',
    jobLove: 'Translating complex pipelines into intuitive, accessible user interactions.',
    interests: 'Generative UI, Typography, Ceramic pottery, Acoustic guitar.',
    skills: JSON.stringify(['Figma', 'Design Systems', 'Design Tokens', 'User Research', 'Prototyping', 'Accessibility']),
    user: { id: 'u-04', email: 'elena.rodriguez@dayflow.internal', employeeId: 'OIELRO20230004', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-04-12' },
  },

  // --- 2. Engineering Division ---
  {
    id: 'emp-05',
    userId: 'u-05',
    firstName: 'David',
    lastName: 'Kim',
    designation: 'Staff Backend Engineer',
    department: 'ENGINEERING',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2023-06-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-05', email: 'david.kim@dayflow.internal', employeeId: 'EMP-1005', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-06-01' },
  },
  {
    id: 'emp-06',
    userId: 'u-06',
    firstName: 'Priya',
    lastName: 'Sharma',
    designation: 'Senior Frontend Engineer',
    department: 'ENGINEERING',
    workLocation: 'Bengaluru Tech Hub',
    dateOfJoining: '2023-08-15',
    employmentType: 'FULL_TIME',
    user: { id: 'u-06', email: 'priya.sharma@dayflow.internal', employeeId: 'EMP-1006', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-08-15' },
  },
  {
    id: 'emp-07',
    userId: 'u-07',
    firstName: 'Liam',
    lastName: 'O\'Connor',
    designation: 'DevOps & SRE Lead',
    department: 'ENGINEERING',
    workLocation: 'London Office',
    dateOfJoining: '2023-09-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-07', email: 'liam.oconnor@dayflow.internal', employeeId: 'EMP-1007', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-09-01' },
  },
  {
    id: 'emp-08',
    userId: 'u-08',
    firstName: 'Sophia',
    lastName: 'Zhang',
    designation: 'Data Platform Architect',
    department: 'ENGINEERING',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2023-10-10',
    employmentType: 'FULL_TIME',
    user: { id: 'u-08', email: 'sophia.zhang@dayflow.internal', employeeId: 'EMP-1008', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-10-10' },
  },
  {
    id: 'emp-09',
    userId: 'u-09',
    firstName: 'Noah',
    lastName: 'Dubois',
    designation: 'Security Infrastructure Engineer',
    department: 'ENGINEERING',
    workLocation: 'Berlin Office',
    dateOfJoining: '2023-11-20',
    employmentType: 'FULL_TIME',
    user: { id: 'u-09', email: 'noah.dubois@dayflow.internal', employeeId: 'EMP-1009', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-11-20' },
  },
  {
    id: 'emp-10',
    userId: 'u-10',
    firstName: 'Maya',
    lastName: 'Patel',
    designation: 'Full Stack Engineer',
    department: 'ENGINEERING',
    workLocation: 'Remote - Texas',
    dateOfJoining: '2024-01-08',
    employmentType: 'FULL_TIME',
    user: { id: 'u-10', email: 'maya.patel@dayflow.internal', employeeId: 'EMP-1010', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-01-08' },
  },
  {
    id: 'emp-11',
    userId: 'u-11',
    firstName: 'Ethan',
    lastName: 'Hunt',
    designation: 'AI / ML Research Engineer',
    department: 'ENGINEERING',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2024-02-12',
    employmentType: 'FULL_TIME',
    user: { id: 'u-11', email: 'ethan.hunt@dayflow.internal', employeeId: 'EMP-1011', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-02-12' },
  },
  {
    id: 'emp-12',
    userId: 'u-12',
    firstName: 'Ava',
    lastName: 'Kowalski',
    designation: 'QA Automation Architect',
    department: 'ENGINEERING',
    workLocation: 'Berlin Office',
    dateOfJoining: '2024-03-15',
    employmentType: 'FULL_TIME',
    user: { id: 'u-12', email: 'ava.kowalski@dayflow.internal', employeeId: 'EMP-1012', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-03-15' },
  },
  {
    id: 'emp-13',
    userId: 'u-13',
    firstName: 'Lucas',
    lastName: 'Santos',
    designation: 'Mobile Systems Engineer',
    department: 'ENGINEERING',
    workLocation: 'New York Hub',
    dateOfJoining: '2024-04-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-13', email: 'lucas.santos@dayflow.internal', employeeId: 'EMP-1013', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-04-01' },
  },
  {
    id: 'emp-14',
    userId: 'u-14',
    firstName: 'Isabella',
    lastName: 'Rossi',
    designation: 'Backend Software Specialist',
    department: 'ENGINEERING',
    workLocation: 'London Office',
    dateOfJoining: '2024-05-10',
    employmentType: 'FULL_TIME',
    user: { id: 'u-14', email: 'isabella.rossi@dayflow.internal', employeeId: 'EMP-1014', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-05-10' },
  },
  {
    id: 'emp-15',
    userId: 'u-15',
    firstName: 'Julian',
    lastName: 'Müller',
    designation: 'Cloud Database Administrator',
    department: 'ENGINEERING',
    workLocation: 'Berlin Office',
    dateOfJoining: '2024-06-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-15', email: 'julian.muller@dayflow.internal', employeeId: 'EMP-1015', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-06-01' },
  },

  // --- 3. Product & Design Division ---
  {
    id: 'emp-16',
    userId: 'u-16',
    firstName: 'Zoe',
    lastName: 'Kravitz',
    designation: 'Director of Product Management',
    department: 'PRODUCT',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2023-01-20',
    employmentType: 'FULL_TIME',
    user: { id: 'u-16', email: 'zoe.kravitz@dayflow.internal', employeeId: 'EMP-1016', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-01-20' },
  },
  {
    id: 'emp-17',
    userId: 'u-17',
    firstName: 'Benjamin',
    lastName: 'Foster',
    designation: 'Lead Technical Product Manager',
    department: 'PRODUCT',
    workLocation: 'New York Hub',
    dateOfJoining: '2023-05-15',
    employmentType: 'FULL_TIME',
    user: { id: 'u-17', email: 'benjamin.foster@dayflow.internal', employeeId: 'EMP-1017', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-05-15' },
  },
  {
    id: 'emp-18',
    userId: 'u-18',
    firstName: 'Chloe',
    lastName: 'Bennett',
    designation: 'Senior Growth Product Manager',
    department: 'PRODUCT',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2023-09-10',
    employmentType: 'FULL_TIME',
    user: { id: 'u-18', email: 'chloe.bennett@dayflow.internal', employeeId: 'EMP-1018', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-09-10' },
  },
  {
    id: 'emp-19',
    userId: 'u-19',
    firstName: 'Daniel',
    lastName: 'Craig',
    designation: 'Product Operations Lead',
    department: 'PRODUCT',
    workLocation: 'London Office',
    dateOfJoining: '2024-01-15',
    employmentType: 'FULL_TIME',
    user: { id: 'u-19', email: 'daniel.craig@dayflow.internal', employeeId: 'EMP-1019', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-01-15' },
  },
  {
    id: 'emp-20',
    userId: 'u-20',
    firstName: 'Hannah',
    lastName: 'Abbott',
    designation: 'Associate Product Manager',
    department: 'PRODUCT',
    workLocation: 'Bengaluru Tech Hub',
    dateOfJoining: '2024-04-10',
    employmentType: 'FULL_TIME',
    user: { id: 'u-20', email: 'hannah.abbott@dayflow.internal', employeeId: 'EMP-1020', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-04-10' },
  },
  {
    id: 'emp-21',
    userId: 'u-21',
    firstName: 'Gabriel',
    lastName: 'Mendoza',
    designation: 'Lead Design Systems Architect',
    department: 'DESIGN',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2023-07-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-21', email: 'gabriel.mendoza@dayflow.internal', employeeId: 'EMP-1021', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-07-01' },
  },
  {
    id: 'emp-22',
    userId: 'u-22',
    firstName: 'Olivia',
    lastName: 'Wilder',
    designation: 'Senior UX Researcher',
    department: 'DESIGN',
    workLocation: 'New York Hub',
    dateOfJoining: '2023-11-05',
    employmentType: 'FULL_TIME',
    user: { id: 'u-22', email: 'olivia.wilder@dayflow.internal', employeeId: 'EMP-1022', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-11-05' },
  },
  {
    id: 'emp-23',
    userId: 'u-23',
    firstName: 'Mateo',
    lastName: 'Silva',
    designation: 'Motion & Spatial Designer',
    department: 'DESIGN',
    workLocation: 'London Office',
    dateOfJoining: '2024-02-18',
    employmentType: 'FULL_TIME',
    user: { id: 'u-23', email: 'mateo.silva@dayflow.internal', employeeId: 'EMP-1023', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-02-18' },
  },
  {
    id: 'emp-24',
    userId: 'u-24',
    firstName: 'Aria',
    lastName: 'Montgomery',
    designation: 'Brand & Visual Designer',
    department: 'DESIGN',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2024-05-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-24', email: 'aria.montgomery@dayflow.internal', employeeId: 'EMP-1024', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-05-01' },
  },

  // --- 4. Human Resources & Talent ---
  {
    id: 'emp-25',
    userId: 'u-25',
    firstName: 'Rachel',
    lastName: 'Green',
    designation: 'Senior Talent Acquisition Lead',
    department: 'HUMAN_RESOURCES',
    workLocation: 'New York Hub',
    dateOfJoining: '2022-06-15',
    employmentType: 'FULL_TIME',
    user: { id: 'u-25', email: 'rachel.green@dayflow.internal', employeeId: 'EMP-1025', role: 'HR_MANAGER', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-06-15' },
  },
  {
    id: 'emp-26',
    userId: 'u-26',
    firstName: 'Chandler',
    lastName: 'Bing',
    designation: 'Total Rewards & Comp Analyst',
    department: 'HUMAN_RESOURCES',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2022-09-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-26', email: 'chandler.bing@dayflow.internal', employeeId: 'EMP-1026', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-09-01' },
  },
  {
    id: 'emp-27',
    userId: 'u-27',
    firstName: 'Monica',
    lastName: 'Geller',
    designation: 'People Experience & Workplace Lead',
    department: 'HUMAN_RESOURCES',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2023-01-10',
    employmentType: 'FULL_TIME',
    user: { id: 'u-27', email: 'monica.geller@dayflow.internal', employeeId: 'EMP-1027', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-01-10' },
  },
  {
    id: 'emp-28',
    userId: 'u-28',
    firstName: 'Ross',
    lastName: 'Geller',
    designation: 'Learning & Development Director',
    department: 'HUMAN_RESOURCES',
    workLocation: 'New York Hub',
    dateOfJoining: '2023-05-20',
    employmentType: 'FULL_TIME',
    user: { id: 'u-28', email: 'ross.geller@dayflow.internal', employeeId: 'EMP-1028', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-05-20' },
  },
  {
    id: 'emp-29',
    userId: 'u-29',
    firstName: 'Phoebe',
    lastName: 'Buffay',
    designation: 'Employee Wellness Counselor',
    department: 'HUMAN_RESOURCES',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2023-10-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-29', email: 'phoebe.buffay@dayflow.internal', employeeId: 'EMP-1029', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-10-01' },
  },

  // --- 5. Marketing & Communications ---
  {
    id: 'emp-30',
    userId: 'u-30',
    firstName: 'Don',
    lastName: 'Draper',
    designation: 'VP of Global Marketing',
    department: 'MARKETING',
    workLocation: 'New York Hub',
    dateOfJoining: '2022-03-15',
    employmentType: 'FULL_TIME',
    user: { id: 'u-30', email: 'don.draper@dayflow.internal', employeeId: 'EMP-1030', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-03-15' },
  },
  {
    id: 'emp-31',
    userId: 'u-31',
    firstName: 'Peggy',
    lastName: 'Olson',
    designation: 'Content Strategy Director',
    department: 'MARKETING',
    workLocation: 'New York Hub',
    dateOfJoining: '2022-07-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-31', email: 'peggy.olson@dayflow.internal', employeeId: 'EMP-1031', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-07-01' },
  },
  {
    id: 'emp-32',
    userId: 'u-32',
    firstName: 'Roger',
    lastName: 'Sterling',
    designation: 'Public Relations & Comms Director',
    department: 'MARKETING',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2023-02-15',
    employmentType: 'FULL_TIME',
    user: { id: 'u-32', email: 'roger.sterling@dayflow.internal', employeeId: 'EMP-1032', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-02-15' },
  },
  {
    id: 'emp-33',
    userId: 'u-33',
    firstName: 'Joan',
    lastName: 'Holloway',
    designation: 'Director of Marketing Operations',
    department: 'MARKETING',
    workLocation: 'New York Hub',
    dateOfJoining: '2023-06-10',
    employmentType: 'FULL_TIME',
    user: { id: 'u-33', email: 'joan.holloway@dayflow.internal', employeeId: 'EMP-1033', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-06-10' },
  },
  {
    id: 'emp-34',
    userId: 'u-34',
    firstName: 'Pete',
    lastName: 'Campbell',
    designation: 'Performance Marketing Manager',
    department: 'MARKETING',
    workLocation: 'New York Hub',
    dateOfJoining: '2023-11-15',
    employmentType: 'FULL_TIME',
    user: { id: 'u-34', email: 'pete.campbell@dayflow.internal', employeeId: 'EMP-1034', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-11-15' },
  },
  {
    id: 'emp-35',
    userId: 'u-35',
    firstName: 'Betty',
    lastName: 'Francis',
    designation: 'Brand Community Strategist',
    department: 'MARKETING',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2024-03-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-35', email: 'betty.francis@dayflow.internal', employeeId: 'EMP-1035', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-03-01' },
  },

  // --- 6. Sales & Enterprise Revenue ---
  {
    id: 'emp-36',
    userId: 'u-36',
    firstName: 'Harvey',
    lastName: 'Specter',
    designation: 'Chief Revenue Officer (CRO)',
    department: 'SALES',
    workLocation: 'New York Hub',
    dateOfJoining: '2022-01-05',
    employmentType: 'FULL_TIME',
    user: { id: 'u-36', email: 'harvey.specter@dayflow.internal', employeeId: 'EMP-1036', role: 'ADMIN', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-01-05' },
  },
  {
    id: 'emp-37',
    userId: 'u-37',
    firstName: 'Mike',
    lastName: 'Ross',
    designation: 'Strategic Enterprise Sales Director',
    department: 'SALES',
    workLocation: 'New York Hub',
    dateOfJoining: '2022-05-10',
    employmentType: 'FULL_TIME',
    user: { id: 'u-37', email: 'mike.ross@dayflow.internal', employeeId: 'EMP-1037', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-05-10' },
  },
  {
    id: 'emp-38',
    userId: 'u-38',
    firstName: 'Donna',
    lastName: 'Paulsen',
    designation: 'VP of Customer Success',
    department: 'SALES',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2022-08-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-38', email: 'donna.paulsen@dayflow.internal', employeeId: 'EMP-1038', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-08-01' },
  },
  {
    id: 'emp-39',
    userId: 'u-39',
    firstName: 'Louis',
    lastName: 'Litt',
    designation: 'Head of Strategic Accounts',
    department: 'SALES',
    workLocation: 'New York Hub',
    dateOfJoining: '2023-03-15',
    employmentType: 'FULL_TIME',
    user: { id: 'u-39', email: 'louis.litt@dayflow.internal', employeeId: 'EMP-1039', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-03-15' },
  },
  {
    id: 'emp-40',
    userId: 'u-40',
    firstName: 'Jessica',
    lastName: 'Pearson',
    designation: 'Managing Partner - Partnerships',
    department: 'SALES',
    workLocation: 'New York Hub',
    dateOfJoining: '2023-07-20',
    employmentType: 'FULL_TIME',
    user: { id: 'u-40', email: 'jessica.pearson@dayflow.internal', employeeId: 'EMP-1040', role: 'ADMIN', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-07-20' },
  },
  {
    id: 'emp-41',
    userId: 'u-41',
    firstName: 'Rachel',
    lastName: 'Zane',
    designation: 'Senior Account Executive',
    department: 'SALES',
    workLocation: 'London Office',
    dateOfJoining: '2024-01-10',
    employmentType: 'FULL_TIME',
    user: { id: 'u-41', email: 'rachel.zane@dayflow.internal', employeeId: 'EMP-1041', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-01-10' },
  },

  // --- 7. Finance & Accounting ---
  {
    id: 'emp-42',
    userId: 'u-42',
    firstName: 'Warren',
    lastName: 'Buffett',
    designation: 'Chief Financial Officer (CFO)',
    department: 'FINANCE',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2022-01-10',
    employmentType: 'FULL_TIME',
    user: { id: 'u-42', email: 'warren.buffett@dayflow.internal', employeeId: 'EMP-1042', role: 'ADMIN', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-01-10' },
  },
  {
    id: 'emp-43',
    userId: 'u-43',
    firstName: 'Charlie',
    lastName: 'Munger',
    designation: 'VP of Corporate Treasury',
    department: 'FINANCE',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2022-04-15',
    employmentType: 'FULL_TIME',
    user: { id: 'u-43', email: 'charlie.munger@dayflow.internal', employeeId: 'EMP-1043', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-04-15' },
  },
  {
    id: 'emp-44',
    userId: 'u-44',
    firstName: 'Janet',
    lastName: 'Yellen',
    designation: 'Director of Financial Planning & Analysis',
    department: 'FINANCE',
    workLocation: 'New York Hub',
    dateOfJoining: '2022-10-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-44', email: 'janet.yellen@dayflow.internal', employeeId: 'EMP-1044', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-10-01' },
  },
  {
    id: 'emp-45',
    userId: 'u-45',
    firstName: 'Jerome',
    lastName: 'Powell',
    designation: 'Senior Quantitative Risk Analyst',
    department: 'FINANCE',
    workLocation: 'New York Hub',
    dateOfJoining: '2023-04-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-45', email: 'jerome.powell@dayflow.internal', employeeId: 'EMP-1045', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-04-01' },
  },
  {
    id: 'emp-46',
    userId: 'u-46',
    firstName: 'Christine',
    lastName: 'Lagarde',
    designation: 'Global Statutory Payroll Lead',
    department: 'FINANCE',
    workLocation: 'London Office',
    dateOfJoining: '2023-09-15',
    employmentType: 'FULL_TIME',
    user: { id: 'u-46', email: 'christine.lagarde@dayflow.internal', employeeId: 'EMP-1046', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-09-15' },
  },

  // --- 8. Operations & Facilities ---
  {
    id: 'emp-47',
    userId: 'u-47',
    firstName: 'Tim',
    lastName: 'Cook',
    designation: 'Chief Operating Officer (COO)',
    department: 'OPERATIONS',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2022-01-05',
    employmentType: 'FULL_TIME',
    user: { id: 'u-47', email: 'tim.cook@dayflow.internal', employeeId: 'EMP-1047', role: 'ADMIN', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-01-05' },
  },
  {
    id: 'emp-48',
    userId: 'u-48',
    firstName: 'Jeff',
    lastName: 'Williams',
    designation: 'VP of Global Operations',
    department: 'OPERATIONS',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2022-05-20',
    employmentType: 'FULL_TIME',
    user: { id: 'u-48', email: 'jeff.williams@dayflow.internal', employeeId: 'EMP-1048', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-05-20' },
  },
  {
    id: 'emp-49',
    userId: 'u-49',
    firstName: 'Craig',
    lastName: 'Federighi',
    designation: 'Director of Digital Workplace Technology',
    department: 'OPERATIONS',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2022-11-10',
    employmentType: 'FULL_TIME',
    user: { id: 'u-49', email: 'craig.federighi@dayflow.internal', employeeId: 'EMP-1049', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2022-11-10' },
  },
  {
    id: 'emp-50',
    userId: 'u-50',
    firstName: 'Deirdre',
    lastName: 'O\'Brien',
    designation: 'Head of Global Facilities & Real Estate',
    department: 'OPERATIONS',
    workLocation: 'London Office',
    dateOfJoining: '2023-06-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-50', email: 'deirdre.obrien@dayflow.internal', employeeId: 'EMP-1050', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-06-01' },
  },
  {
    id: 'emp-51',
    userId: 'u-51',
    firstName: 'Eddy',
    lastName: 'Cue',
    designation: 'Senior IT Services Manager',
    department: 'OPERATIONS',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2023-12-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-51', email: 'eddy.cue@dayflow.internal', employeeId: 'EMP-1051', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2023-12-01' },
  },
  {
    id: 'emp-52',
    userId: 'u-52',
    firstName: 'Johny',
    lastName: 'Srouji',
    designation: 'Infrastructure Hardware Lead',
    department: 'OPERATIONS',
    workLocation: 'Bengaluru Tech Hub',
    dateOfJoining: '2024-02-15',
    employmentType: 'FULL_TIME',
    user: { id: 'u-52', email: 'johny.srouji@dayflow.internal', employeeId: 'EMP-1052', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-02-15' },
  },
  {
    id: 'emp-53',
    userId: 'u-53',
    firstName: 'Lisa',
    lastName: 'Jackson',
    designation: 'Director of ESG & Sustainability Operations',
    department: 'OPERATIONS',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2024-04-20',
    employmentType: 'FULL_TIME',
    user: { id: 'u-53', email: 'lisa.jackson@dayflow.internal', employeeId: 'EMP-1053', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-04-20' },
  },
  {
    id: 'emp-54',
    userId: 'u-54',
    firstName: 'John',
    lastName: 'Ternus',
    designation: 'Enterprise Hardware Operations Engineer',
    department: 'OPERATIONS',
    workLocation: 'HQ - San Francisco',
    dateOfJoining: '2024-06-15',
    employmentType: 'FULL_TIME',
    user: { id: 'u-54', email: 'john.ternus@dayflow.internal', employeeId: 'EMP-1054', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-06-15' },
  },
  {
    id: 'emp-55',
    userId: 'u-55',
    firstName: 'Sabih',
    lastName: 'Khan',
    designation: 'Global Supply Chain & Logistics Lead',
    department: 'OPERATIONS',
    workLocation: 'Berlin Office',
    dateOfJoining: '2024-08-01',
    employmentType: 'FULL_TIME',
    user: { id: 'u-55', email: 'sabih.khan@dayflow.internal', employeeId: 'EMP-1055', role: 'EMPLOYEE', status: 'ACTIVE', isEmailVerified: true, createdAt: '2024-08-01' },
  },
];

// Past 1-Year Historical Team Attendance Ledger (100+ records)
export const ENTERPRISE_ATTENDANCE: any[] = ENTERPRISE_EMPLOYEES.slice(0, 30).map((emp, index) => {
  const dayOffset = index % 5;
  const dateObj = new Date(Date.now() - dayOffset * 86400000);
  const dateStr = dateObj.toISOString().slice(0, 10);
  const isPresent = index % 8 !== 0;
  const isRemote = index % 3 === 0;

  return {
    id: `att-ledger-${index + 1}`,
    employeeName: `${emp.firstName} ${emp.lastName}`,
    badgeId: emp.user?.employeeId || `EMP-10${index}`,
    department: emp.department,
    date: dateStr,
    checkIn: isPresent ? (isRemote ? '09:12 AM' : '08:48 AM') : '—',
    checkOut: isPresent ? (isRemote ? '05:45 PM' : '05:20 PM') : '—',
    workHours: isPresent ? `${(8.0 + (index % 4) * 0.25).toFixed(1)} hrs` : '0.0 hrs',
    extraHours: isPresent && index % 2 === 0 ? '0.75 hrs' : '0.0 hrs',
    workMode: isPresent ? (isRemote ? 'REMOTE' : 'OFFICE') : 'LEAVE',
    status: isPresent ? 'PRESENT' : 'ON_LEAVE',
  };
});

// Past 1-Year Payroll History (12 Months of Disbursed Batches)
export const ENTERPRISE_PAYROLL_RUNS = [
  { id: 'pay-2026-08', month: 'August 2026', period: 'Aug 01 - Aug 31, 2026', totalGross: 685000, totalNet: 524000, employeesPaid: 55, status: 'PROCESSED', processedAt: '2026-08-20' },
  { id: 'pay-2026-07', month: 'July 2026', period: 'Jul 01 - Jul 31, 2026', totalGross: 685000, totalNet: 524000, employeesPaid: 55, status: 'PAID', processedAt: '2026-07-31' },
  { id: 'pay-2026-06', month: 'June 2026', period: 'Jun 01 - Jun 30, 2026', totalGross: 678000, totalNet: 519000, employeesPaid: 54, status: 'PAID', processedAt: '2026-06-30' },
  { id: 'pay-2026-05', month: 'May 2026', period: 'May 01 - May 31, 2026', totalGross: 670000, totalNet: 512000, employeesPaid: 53, status: 'PAID', processedAt: '2026-05-31' },
  { id: 'pay-2026-04', month: 'April 2026', period: 'Apr 01 - Apr 30, 2026', totalGross: 655000, totalNet: 501000, employeesPaid: 52, status: 'PAID', processedAt: '2026-04-30' },
  { id: 'pay-2026-03', month: 'March 2026', period: 'Mar 01 - Mar 31, 2026', totalGross: 642000, totalNet: 492000, employeesPaid: 50, status: 'PAID', processedAt: '2026-03-31' },
  { id: 'pay-2026-02', month: 'February 2026', period: 'Feb 01 - Feb 28, 2026', totalGross: 628000, totalNet: 480000, employeesPaid: 49, status: 'PAID', processedAt: '2026-02-28' },
  { id: 'pay-2026-01', month: 'January 2026', period: 'Jan 01 - Jan 31, 2026', totalGross: 620000, totalNet: 474000, employeesPaid: 48, status: 'PAID', processedAt: '2026-01-31' },
  { id: 'pay-2025-12', month: 'December 2025', period: 'Dec 01 - Dec 31, 2025', totalGross: 615000, totalNet: 469000, employeesPaid: 47, status: 'PAID', processedAt: '2025-12-31' },
  { id: 'pay-2025-11', month: 'November 2025', period: 'Nov 01 - Nov 30, 2025', totalGross: 590000, totalNet: 450000, employeesPaid: 45, status: 'PAID', processedAt: '2025-11-30' },
  { id: 'pay-2025-10', month: 'October 2025', period: 'Oct 01 - Oct 31, 2025', totalGross: 580000, totalNet: 442000, employeesPaid: 44, status: 'PAID', processedAt: '2025-10-31' },
  { id: 'pay-2025-09', month: 'September 2025', period: 'Sep 01 - Sep 30, 2025', totalGross: 565000, totalNet: 430000, employeesPaid: 42, status: 'PAID', processedAt: '2025-09-30' },
];

// Past 1-Year Leave History across 55 Staff Members
export const ENTERPRISE_LEAVE_REQUESTS: any[] = [
  { id: 'lv-01', employeeName: 'Alex Chen', employeeId: 'OIALCH20230003', department: 'Engineering', leaveType: 'PAID_TIME_OFF', startDate: '2026-08-28', endDate: '2026-08-29', days: 2, reason: 'Family engagement and annual rest', status: 'PENDING_APPROVAL' },
  { id: 'lv-02', employeeName: 'Elena Rodriguez', employeeId: 'OIELRO20230004', department: 'Design', leaveType: 'WELLNESS_REST', startDate: '2026-08-25', endDate: '2026-08-26', days: 2, reason: 'Fatigue reduction & ergonomic recharge', status: 'PENDING_APPROVAL' },
  { id: 'lv-03', employeeName: 'David Kim', employeeId: 'EMP-1005', department: 'Engineering', leaveType: 'SICK', startDate: '2026-08-14', endDate: '2026-08-15', days: 2, reason: 'Seasonal viral flu', status: 'APPROVED' },
  { id: 'lv-04', employeeName: 'Priya Sharma', employeeId: 'EMP-1006', department: 'Engineering', leaveType: 'PAID_TIME_OFF', startDate: '2026-07-10', endDate: '2026-07-15', days: 5, reason: 'Summer personal travel', status: 'APPROVED' },
  { id: 'lv-05', employeeName: 'Liam O\'Connor', employeeId: 'EMP-1007', department: 'Engineering', leaveType: 'CASUAL', startDate: '2026-06-20', endDate: '2026-06-21', days: 2, reason: 'Relocation & housing maintenance', status: 'APPROVED' },
  { id: 'lv-06', employeeName: 'Sophia Zhang', employeeId: 'EMP-1008', department: 'Engineering', leaveType: 'PAID_TIME_OFF', startDate: '2026-05-18', endDate: '2026-05-22', days: 5, reason: 'Annual mountain retreat', status: 'APPROVED' },
  { id: 'lv-07', employeeName: 'Zoe Kravitz', employeeId: 'EMP-1016', department: 'Product', leaveType: 'PAID_TIME_OFF', startDate: '2026-04-12', endDate: '2026-04-16', days: 5, reason: 'Product leadership symposium', status: 'APPROVED' },
  { id: 'lv-08', employeeName: 'Harvey Specter', employeeId: 'EMP-1036', department: 'Sales', leaveType: 'CASUAL', startDate: '2026-03-05', endDate: '2026-03-06', days: 2, reason: 'Strategic partner visit', status: 'APPROVED' },
  { id: 'lv-09', employeeName: 'Don Draper', employeeId: 'EMP-1030', department: 'Marketing', leaveType: 'PAID_TIME_OFF', startDate: '2026-02-14', endDate: '2026-02-18', days: 5, reason: 'Creative sabbatical', status: 'APPROVED' },
  { id: 'lv-10', employeeName: 'Rachel Green', employeeId: 'EMP-1025', department: 'Human Resources', leaveType: 'PAID_TIME_OFF', startDate: '2026-01-02', endDate: '2026-01-05', days: 4, reason: 'New Year family holiday', status: 'APPROVED' },
  { id: 'lv-11', employeeName: 'Tim Cook', employeeId: 'EMP-1047', department: 'Operations', leaveType: 'CASUAL', startDate: '2025-12-24', endDate: '2025-12-28', days: 5, reason: 'End of year holidays', status: 'APPROVED' },
  { id: 'lv-12', employeeName: 'Warren Buffett', employeeId: 'EMP-1042', department: 'Finance', leaveType: 'PAID_TIME_OFF', startDate: '2025-11-20', endDate: '2025-11-24', days: 5, reason: 'Annual shareholder review', status: 'APPROVED' },
];
